services:
  - type: web
    name: agentech-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run main_google.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
